config:
  client-id: '123456'
  client-secret: 'abcde'
  scopes:
    - 'read'
    - 'write'

multiple:
  fail-over-client:
    class: HttpClientService
    config:
      client-secret: 'abcde'

  default-client:
    class: HttpClientService
    config:
      client-id: 'gggg'
      client-secret: 'abcde'
      scopes:
        - 'read'
        - 'write'
        - 'delete'
