app:
  name: 'best of luck'
  nice: 1
  books:
    - 'thanks'

multiple:
    beana:
      class: Service
      app:
        nice: 2
        books:
          - 'good'
          - 'bad'

    beanb:
      class: Service
